version: '3.8'
services:
  postgresql-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432